alias la='ls -lAFh'
alias grep='grep --color'

alias ga='git add'
alias gaa='git add --all'
alias gap='git apply'
alias gapa='git add --patch'
alias gc='gc_msgfile=$(mktemp); git diff --cached | codex exec --ephemeral -m gpt-5.6-luna -s read-only -o "$gc_msgfile" "Generate ONLY a one-line Git commit message in English using imperative mood, following Conventional Commits format. The message should summarize what changed and why, based strictly on the diff provided in the <stdin> block. DO NOT add an explanation or a body. Output ONLY the commit summary line." > /dev/null && git commit -m "$(cat "$gc_msgfile")" -e; rm -f "$gc_msgfile"; unset gc_msgfile'
alias 'gc!'='git commit --verbose --amend'
alias gcb='git checkout -b'
alias 'gcn!'='git commit --verbose --no-edit --amend'
alias gcmsg='git commit --message'
alias gco='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git pull'
alias glg='git log --stat'
alias glgg='git log --graph'
alias glgga='git log --graph --decorate --all'
alias glo='git log --oneline --decorate'
alias glod='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset"'
alias glog='git log --oneline --decorate --graph'
alias glol='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset"'
alias gp='git push'
alias gpf='git push --force-with-lease --force-if-includes'
alias gsb='git status --short --branch'
alias gss='git status --short'
alias gst='git status'
