shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.dracula-zsh]
github = "dracula/zsh"
use = ["dracula.zsh-theme"]

[plugins.dracula-zsh-post]
inline = '''
  ZSH_THEME_GIT_PROMPT_PREFIX="%F{default}("
  PROMPT='%(1V:%F{yellow}:%(?:%F{green}:%F{red}))%B%# %F{default}%c $DRACULA_GIT_STATUS'
'''

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["zsh-autosuggestions.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
use = ["zsh-syntax-highlighting.zsh"]
