tap "delphinus/sfmono-square"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "asdf"
brew "awscli"
brew "gh"
brew "ghq"
brew "git-secrets"
brew "git"
brew "jq"
brew "kubectx"
brew "kustomize"
brew "mas"
brew "moreutils"
brew "neovim"
brew "pdftk-java"
brew "pnpm"
brew "ripgrep"
brew "sfmono-square"
brew "shellcheck"
brew "stern"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
brew "yq"
brew "zsh"
cask "1password"
cask "alfred"
cask "altair-graphql-client"
cask "anki"
cask "appcleaner"
cask "betterdisplay"
cask "bettertouchtool"
cask "deepl"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "firefox"
cask "flycut"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "lunar"
cask "ngrok"
cask "slack"
cask "tableplus"
cask "visual-studio-code"
cask "zoom"
mas "GoodNotes", id: 1444383602
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Smart Countdown Timer", id: 1410709951
mas "Trello", id: 1278508951
mas "Outlook", id: 985367838
