[tools]
node = "latest"
bun = "latest"
deno = "latest"
rust = "latest"
go = "latest"
ruby = "latest"
python = "latest"
dotnet = "latest"

[settings]
global_config_file = "~/.mise.toml"
idiomatic_version_file_enable_tools = ["node", "ruby"]
