[tools]
node = "latest"
bun = "latest"
deno = "latest"
rust = "latest"
go = "latest"
ruby = "latest"
python = "latest"
dotnet = "latest"
"npm:@antfu/ni" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby"]
