[tools]
node = "latest"
pnpm = "latest"
bun = "latest"
deno = "latest"
rust = "latest"
go = "latest"
ruby = "latest"
python = "latest"
dotnet = "latest"
"npm:@antfu/ni" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@biomejs/biome" = "2.4.8"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby"]
