shell = "zsh"

[plugins.dracula-zsh]
github = "dracula/zsh"
use = ["dracula.zsh-theme"]

[plugins.dracula-zsh-post]
inline = '''
  ZSH_THEME_GIT_PROMPT_PREFIX="%F{default}("
  PROMPT='%(1V:%F{yellow}:%(?:%F{green}:%F{red}))%B%# %F{default}%c $DRACULA_GIT_STATUS'
'''

[plugins.enhancd-pre]
inline = """
  export ENHANCD_COMMAND=c;
  export ENHANCD_FILTER="fzf --height 25% --reverse";
"""

[plugins.enhancd]
github = "b4b4r07/enhancd"

[plugins.fzf]
github = "junegunn/fzf"
# tag = "v0.63.0"

[plugins.fzf-post]
inline = """
  ~/.local/share/sheldon/repos/github.com/junegunn/fzf/install --bin
  cp ~/.local/share/sheldon/repos/github.com/junegunn/fzf/bin/fzf ~/.local/bin
"""

[plugins.fzf-git]
github = "junegunn/fzf-git.sh"

[plugins.ohmyzsh-aliases-pre]
inline = """
  # ref: https://github.com/ohmyzsh/ohmyzsh/blob/97134d1eed19b72a9c4bf90a2effa847221608bf/plugins/docker-compose/docker-compose.plugin.zsh#L2
  alias docker-compose="docker compose"
  # ref: https://github.com/ohmyzsh/ohmyzsh/blob/97134d1eed19b72a9c4bf90a2effa847221608bf/plugins/kubectl/kubectl.plugin.zsh#L5
  export ZSH_CACHE_DIR=~/.cache/zsh
  mkdir -p "$ZSH_CACHE_DIR/completions"
  # ref: https://github.com/ohmyzsh/ohmyzsh/blob/fcd7da3aec8315178991aa25d57dacfc6c331ac6/plugins/common-aliases/common-aliases.plugin.zsh#L5
  alias ls='ls --color'
"""

[plugins.ohmyzsh-aliases]
github = "ohmyzsh/ohmyzsh"
use = [
  "plugins/common-aliases/common-aliases.plugin.zsh", # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/common-aliases
  "plugins/git/git.plugin.zsh",                       # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git
  "plugins/docker/docker.plugin.zsh",                 # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker
  "plugins/docker-compose/docker-compose.plugin.zsh", # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker-compose
  "plugins/kubectl/kubectl.plugin.zsh",               # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/kubectl
]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["zsh-autosuggestions.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
use = ["zsh-syntax-highlighting.zsh"]
